# Foundry configuration for QuestEth smartcontracts
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimize = true
optimizer_runs = 200
solc = "0.8.19"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
