# Foundry configuration for QuestEth smartcontracts
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
optimizer = true
optimizer_runs = 200
via_ir = true
solc = "0.8.24"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

# Mantle Mainnet
[rpc_endpoints]
mantle = "${MANTLE_RPC_URL}"
mantle_testnet = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle = { key = "${MANTLE_API_KEY}", url = "https://explorer.mantle.xyz/api" }
mantle_testnet = { key = "${MANTLE_API_KEY}", url = "https://explorer.testnet.mantle.xyz/api" }
